### ISSUE TITLE
windows的快速安装可以使用

### ISSUE THREAD

**Issue by bestlope** [wwek/haoma#3]
截至2018年8月15日 星期三，windows的快速安装可以使用，但需要搭建在本地使用。
例如：搭建在172.16.1.1这台windows服务器上，在这台服务器的浏览器输入localhost:8888是可以使用服务的，即测试批量查询的默认号码是有反馈的。但是，在其他电脑输入172.16.1.1:8888,可以登录web界面，但是批量查询是不可用的。
这个问题的解决方法：
修改gui/js/app.020fb3ee71079686124d中的127.0.0.1为172.16.1.1（自己的IP），即可。
再次访问的时候记得要强制刷新浏览器，因为浏览器会缓存js文件，导致不能马上看到结果，使用：
ctrl+F5刷新

**Comment by wwek** [comment]
是的，默认设计都是本机使用的。 你有局域网使用的需求。
我改下vue这边的地址

**Comment by wwek** [comment]
https://github.com/wwek/haoma/releases/tag/v0.2
v0.2  已解决，可以局域网访问使用了
