### ISSUE TITLE
查询超过60个之后自动崩溃

### ISSUE THREAD

**Issue by zhq1** [wwek/haoma#4]
查询超过60个号码之后自动崩溃

**Comment by zhq1** [comment]
经发现，应该是360标记引起的，如果360接口调用失败，则一直可以正常调用，如果360能够正常调用，超过30多个之后程序会自动崩溃

**Comment by wwek** [comment]
ok 我来处理下

**Comment by wwek** [comment]
https://github.com/wwek/haoma/releases/tag/v0.2
解决了

**Comment by zhq1** [comment]
还是一样的问题，而且更新后，反而查询到10多个程序就崩溃了，经发现是360检测到IP频繁调用接口就需要输入验证码才能查询，然后就会导致程序崩溃，有没有可能将调用延迟设置大一点来避免360检测到，软件稳定性比查找出来的速度其实更重要些

**Comment by zhq1** [comment]
tang@cdwbcc-PowerEdge-R720:~$ ./haoma-v0.2-linux-amd64
2018/11/07 15:46:09 [I] [asm_amd64.s:1340] http server Running on http://:8888
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x87345a]

goroutine 308 [running]:
github.com/wwek/haoma/vendor/github.com/antchfx/xquery/html.InnerText.func1(0xc00021e930, 0x0)
	/home/travis/gopath/src/github.com/wwek/haoma/vendor/github.com/antchfx/xquery/html/query.go:91 +0x2a
github.com/wwek/haoma/vendor/github.com/antchfx/xquery/html.InnerText(0x0, 0x9c035b, 0x17)
	/home/travis/gopath/src/github.com/wwek/haoma/vendor/github.com/antchfx/xquery/html/query.go:104 +0x84
github.com/wwek/haoma/libs/phone.(*Phone).Query_360shoujiweishi(0xc0003aa980, 0x1, 0xc00031bc5e, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/wwek/haoma/libs/phone/360shoujiweishi.go:61 +0x40a
github.com/wwek/haoma/libs/phone.(*Phone).QueryAll.func1(0xc0003aa980, 0xc0002df920)
	/home/travis/gopath/src/github.com/wwek/haoma/libs/phone/phone.go:54 +0x60
created by github.com/wwek/haoma/libs/phone.(*Phone).QueryAll
	/home/travis/gopath/src/github.com/wwek/haoma/libs/phone/phone.go:53 +0x71

**Comment by wowojyc** [comment]
ip被限制的问题有解吗
